services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=8080
    restart: unless-stopped
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
volumes:
    dragonflydata:

networks:
  default:
    name: backend-network
    external: true
